import type { AnalyseResult } from "./types";

export const DEMO_RESULT: AnalyseResult = {
  vehicule: {
    marque: "Renault",
    modele: "Clio IV",
    immatriculation: "FG-123-AB",
    annee: "2017",
    kilometrage: 98450,
  },
  code_postal: "40100",
  score_sante: 62,
  defaillances: [
    {
      code: "1.1.13.a.2",
      libelle: "Plaquettes de frein arrière usées",
      description:
        "Les plaquettes qui servent à ralentir vos roues arrière sont trop fines. Votre freinage est moins efficace, surtout en cas d'urgence.",
      gravite: "majeur",
      localisation: "ARG, ARD",
      cout_min: 40,
      cout_max: 110,
      cout_moyen: 75,
      cout_piece: "Pièce : 15-45€",
      cout_main_oeuvre: "Main-d'œuvre : 25-65€",
      priorite: 1,
      reparation: "Remplacement des plaquettes + vérification des disques",
      peut_faire_soi_meme: true,
    },
    {
      code: "4.3.2.b.1",
      libelle: "Fuite légère d'échappement",
      description:
        "Un petit trou ou une jointure défaillante laisse passer les gaz d'échappement. Vous avez peut-être remarqué un bruit plus fort au démarrage.",
      gravite: "majeur",
      localisation: "AR",
      cout_min: 80,
      cout_max: 180,
      cout_moyen: 130,
      cout_piece: "Pièce : 20-60€",
      cout_main_oeuvre: "Main-d'œuvre : 60-120€",
      priorite: 1,
      reparation: "Remplacement du joint ou soudure de la ligne d'échappement",
      peut_faire_soi_meme: false,
    },
    {
      code: "7.1.2.a.1",
      libelle: "Phare avant droit mal réglé",
      description:
        "Le faisceau lumineux de votre phare droit est trop haut, ce qui peut éblouir les conducteurs en face la nuit.",
      gravite: "mineur",
      localisation: "AVD",
      cout_min: 25,
      cout_max: 50,
      cout_moyen: 38,
      cout_piece: "Pièce : 0€",
      cout_main_oeuvre: "Main-d'œuvre : 25-50€",
      priorite: 3,
      reparation: "Réglage de la hauteur du phare en atelier",
      peut_faire_soi_meme: false,
    },
    {
      code: "5.1.1.a.2",
      libelle: "Pneu avant gauche usé",
      description:
        "Le pneu a atteint la limite légale d'usure (1.6mm). Il n'assure plus un freinage correct sur sol mouillé.",
      gravite: "majeur",
      localisation: "AVG",
      cout_min: 45,
      cout_max: 90,
      cout_moyen: 68,
      cout_piece: "Pièce : 30-60€",
      cout_main_oeuvre: "Main-d'œuvre : 15-30€",
      priorite: 1,
      reparation: "Remplacement du pneu + vérification du parallélisme",
      peut_faire_soi_meme: false,
    },
    {
      code: "6.2.3.a.1",
      libelle: "Corrosion légère sur berceau",
      description:
        "De la rouille superficielle est apparue sur la pièce métallique qui soutient le moteur. Ce n'est pas dangereux pour l'instant mais à surveiller.",
      gravite: "mineur",
      localisation: "AV",
      cout_min: 100,
      cout_max: 250,
      cout_moyen: 175,
      cout_piece: "Pièce : 20-50€",
      cout_main_oeuvre: "Main-d'œuvre : 80-200€",
      priorite: 3,
      reparation: "Traitement anti-corrosion + peinture de protection",
      peut_faire_soi_meme: false,
    },
  ],
  cout_total_min: 290,
  cout_total_max: 680,
  cote_argus_estimee: null,
  verdict: "reparer",
  conseil_verdict:
    "Le coût total reste raisonnable pour une Clio de 2017. Les réparations obligatoires (frein, échappement, pneu) sont prioritaires pour passer la contre-visite.",
  contre_visite_deadline: "15/05/2026",
  conseils: [
    "Faites faire les freins et le pneu en priorité : ce sont les défaillances qui bloquent la contre-visite.",
    "Demandez 2-3 devis à des garages indépendants plutôt qu'en concession — vous économiserez 20 à 30%.",
    "La corrosion sur le berceau n'est pas bloquante mais traitez-la avant l'hiver prochain pour éviter qu'elle s'aggrave.",
  ],
};
